### ISSUE TITLE
Fails to compile with GCC 4.8

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#166]
The FLiT library fails to compile with GCC 4.8, even though that version supposedly supports C++11.  The error obtained is

```bash
g++  -Wuninitialized -g -fPIC -std=c++11 -Wno-shift-count-overflow -Wall -Wextra -I.  -MD -MF src/flitHelpers.d -c src/flitHelpers.cpp -o src/flitHelpers.o
In file included from src/flitHelpers.cpp:88:0:
src/flitHelpers.h: In function 'std::ifstream flit::ifopen(const string&)':
src/flitHelpers.h:189:49: error: use of deleted function 'std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)'
   return _openfile_check<std::ifstream>(filename);
```

This works in later compilers, but maybe only because the `flit::ifopen()` function is inlined.  It would be good to try to see if this problem is reproduced by the `-fno-inline` compiler flag (or something close to that, I don't remember).

Regardless of whether the FLiT code is valid, it should be changed because we want to officially support GCC 4.8.  So even if this is a bug with GCC 4.8, we will consider it a bug here and change our code to handle it.

**Comment by mikebentley15** [comment]
Fixed in pull request #167
